version: '3.8'

services:
  # ---------------------------------------------------------------------------
  # CAPA DE DATOS: CLÚSTER REDIS (Alta Disponibilidad)
  # Usamos la imagen 'redis-stack' porque incluye el módulo TimeSeries necesario.
  # ---------------------------------------------------------------------------
  
  # 1. El Maestro (Líder inicial)
  redis-master:
    image: redis/redis-stack:7.2.0-v9
    hostname: redis-master
    container_name: redis-master
    # Comando crítico: Carga TimeSeries + Persistencia + Contraseña
    command: >
      bash -c "redis-server --loadmodule /opt/redis-stack/lib/redistimeseries.so 
      --appendonly yes --requirepass supersecret"
    ports:
      - "6379:6379"
    networks:
      - industrial-net
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "supersecret", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # 2. La Réplica (Seguidor)
  redis-replica:
    image: redis/redis-stack:7.2.0-v9
    hostname: redis-replica
    container_name: redis-replica
    # 'replicaof' le dice que copie todo lo que pase en el master
    command: >
      bash -c "redis-server --loadmodule /opt/redis-stack/lib/redistimeseries.so 
      --appendonly yes --replicaof redis-master 6379 --masterauth supersecret --requirepass supersecret"
    depends_on:
      - redis-master
    networks:
      - industrial-net

  # ---------------------------------------------------------------------------
  # CAPA DE ARBITRAJE: SENTINELS
  # Necesitamos 3 para tener consenso (Quórum de 2) si uno muere.
  # ---------------------------------------------------------------------------
  
  sentinel-1:
    image: redis/redis-stack:7.2.0-v9
    container_name: sentinel-1
    # Lógica de Sentinel:
    # - Monitoriza al host 'redis-master'
    # - Si falla 5s (5000ms), se considera caído.
    # - Se requieren 2 votos para elegir nuevo líder.
    command: >
      bash -c "echo 'port 26379' > sentinel.conf &&
      echo 'sentinel monitor mymaster redis-master 6379 2' >> sentinel.conf &&
      echo 'sentinel auth-pass mymaster supersecret' >> sentinel.conf &&
      echo 'sentinel down-after-milliseconds mymaster 5000' >> sentinel.conf &&
      echo 'sentinel failover-timeout mymaster 10000' >> sentinel.conf &&
      echo 'sentinel resolve-hostnames yes' >> sentinel.conf &&
      redis-sentinel sentinel.conf"
    depends_on:
      - redis-master
    networks:
      - industrial-net

  sentinel-2:
    image: redis/redis-stack:7.2.0-v9
    container_name: sentinel-2
    command: >
      bash -c "echo 'port 26379' > sentinel.conf &&
      echo 'sentinel monitor mymaster redis-master 6379 2' >> sentinel.conf &&
      echo 'sentinel auth-pass mymaster supersecret' >> sentinel.conf &&
      echo 'sentinel down-after-milliseconds mymaster 5000' >> sentinel.conf &&
      echo 'sentinel failover-timeout mymaster 10000' >> sentinel.conf &&
      echo 'sentinel resolve-hostnames yes' >> sentinel.conf &&
      redis-sentinel sentinel.conf"
    depends_on:
      - redis-master
    networks:
      - industrial-net

  sentinel-3:
    image: redis/redis-stack:7.2.0-v9
    container_name: sentinel-3
    command: >
      bash -c "echo 'port 26379' > sentinel.conf &&
      echo 'sentinel monitor mymaster redis-master 6379 2' >> sentinel.conf &&
      echo 'sentinel auth-pass mymaster supersecret' >> sentinel.conf &&
      echo 'sentinel down-after-milliseconds mymaster 5000' >> sentinel.conf &&
      echo 'sentinel failover-timeout mymaster 10000' >> sentinel.conf &&
      echo 'sentinel resolve-hostnames yes' >> sentinel.conf &&
      redis-sentinel sentinel.conf"
    depends_on:
      - redis-master
    networks:
      - industrial-net

  # ---------------------------------------------------------------------------
  # CAPA DE APLICACIÓN
  # ---------------------------------------------------------------------------
  web:
    build: 
      context: .
      dockerfile: app/Dockerfile
    #image: dieguccio/api_deteccion_anomalias:v3.2
    
    #platform: linux/amd64

    ports:
      - "8000:8000"
    environment:
      # Inyección de configuración (12-Factor App)
      # Apuntamos a los sentinels, NO al master directamente
      - REDIS_SENTINEL_HOST=sentinel-1
      - REDIS_SENTINEL_PORT=26379
      - REDIS_MASTER_SET=mymaster
      - REDIS_PASSWORD=supersecret
    depends_on:
      - sentinel-1
      - sentinel-2
      - sentinel-3
    networks:
      - industrial-net

  # ---------------------------------------------------------------------------
  # CAPA DE OBSERVABILIDAD
  # ---------------------------------------------------------------------------
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=redis-datasource
    networks:
      - industrial-net

# Red virtual aislada para simular la LAN de la fábrica
networks:
  industrial-net:
    driver: bridge